### PR TITLE
Fix build with newer haskell-gi.

### PR DESCRIPTION
**Pull request by arrowd**

### CODE REVIEW

**Comment by portnov** [comment]
Could you please fix travis build. If you think the problem is in old stack or lts, please update travis.yml accordingly.

**Comment by arrowd** [comment]
Sigh. It seems, this should wait a bit.

**Comment by arrowd** [comment]
Should be OK to merge now.

**Comment by arrowd** [comment]
Thanks! Can we get a new Hackage release now?

**Comment by portnov** [comment]
Ok, will do shortly.

**Comment by portnov** [comment]
done.

**Pull request merged**
