### PR TITLE
Update for GHC 9.2.2

### PR DESCRIPTION
**Pull request by arrowd**

### CODE REVIEW

**Comment by arrowd** [comment]
Bump.

**Comment by portnov** [comment]
Does it still compile with earlier GHC?

**Comment by arrowd** [comment]
I can check. What versions are you interested in?

**Comment by portnov** [comment]
Currently I use 8.8.4. Is it considered too old?

**Comment by arrowd** [comment]
I'd say yes. I mainly use 8.10.7

**Comment by portnov** [comment]
Okay. Does this compile with 8.10.7? :)

**Comment by arrowd** [comment]
Aye, builds fine.

**Comment by portnov** [comment]
Ok.

**Comment by arrowd** [comment]
Can we now get a new release on Hackage?

**Comment by portnov** [comment]
Uploaded version 0.1.0.2.

**Comment by arrowd** [comment]
Great thanks!

**Pull request merged**
